---
title: "Append_T0_Update_Smartie_Final"
author: "Sander"
date: "3 April 2018"
output: pdf_document
---

```{r Libraries}
library(tidyverse)
```

```{r Data}
SMARTIE <- read_csv(file = "./Private/Final_export_2018-03-29_18-47-59.csv", col_types = cols(.default = "c"))
T0 <- read_csv(file = "G://Mijn Drive/INBOPRJ-10217 - Monitoring exoten ikv EU- verordening IAS  Coördinatie, voorbereiding, implementatie en opvolging/data/SMARTIE/T0 Update/invasive_EU_listed_and_considered_with_joins.csv")
aggregated_checklist <- read_delim("https://raw.githubusercontent.com/inbo/alien-species-checklist/master/data/processed/aggregated-checklist.tsv", 
    "\t", escape_double = FALSE, trim_ws = TRUE)
```
```{r split SMARTIE}
SMARTIE1 <- SMARTIE[0:65299,]
SMARTIE1$aanleverDatum <- as.Date(SMARTIE1$aanleverDatum)
SMARTIE1$coordinateUncertaintyInMeters <- as.numeric(SMARTIE1$coordinateUncertaintyInMeters)
SMARTIE1$date_length <- as.numeric(SMARTIE1$date_length)
SMARTIE1$decimalLatitude <- as.numeric(SMARTIE1$decimalLatitude)
SMARTIE1$decimalLongitude <- as.numeric(SMARTIE1$decimalLongitude)
SMARTIE1$gbifapi_speciesKey <- as.numeric(SMARTIE1$gbifapi_speciesKey)
SMARTIE1$gbifapi_usageKey <- as.numeric(SMARTIE1$gbifapi_usageKey)


SMARTIE2 <- SMARTIE[65300:nrow(SMARTIE),]
SMARTIE3 <- SMARTIE2

SMARTIE3$Fiche_ID <- NA
SMARTIE3$FilenameID <- SMARTIE2$Fiche_ID
SMARTIE3$Modified <- NA
SMARTIE3$ObjectID <- NA
SMARTIE3$ProviderID <- SMARTIE2$FilenameID
SMARTIE3$StateProvince <- NA
SMARTIE3$aanleverDatum <- as.Date(SMARTIE2$Modified)
SMARTIE3$associatedTaxa <- NA
SMARTIE3$basisOfRecord <- NA
SMARTIE3$behavior <- NA
SMARTIE3$canonicalName <- NA
SMARTIE3$collectionCode <- NA
SMARTIE3$collectionID <- NA
SMARTIE3$coordinateUncertaintyInMeters <- as.numeric(SMARTIE2$ObjectID)
SMARTIE3$countryCode <- NA
SMARTIE3$dataGeneralizations <- NA
SMARTIE3$datasetName <- SMARTIE2$gbifapi_status
SMARTIE3$dateIdentified <- NA
SMARTIE3$date_length <- NA
SMARTIE3$decimalLatitude <- as.numeric(SMARTIE2$eventDate)
SMARTIE3$decimalLongitude <- as.numeric(SMARTIE2$file_patch)
SMARTIE3$establishmentMeans <- NA
SMARTIE3$eventDate <- SMARTIE2$associatedTaxa
SMARTIE3$file_patch <- NA
SMARTIE3$fips <- NA
SMARTIE3$firstAppearance <- SMARTIE2$basisOfRecord
SMARTIE3$gbifapi_matchType <- SMARTIE2$canonicalName
SMARTIE3$gbifapi_rank <-  SMARTIE2$collectionCode
SMARTIE3$gbifapi_scientificName <- SMARTIE2$collectionID
SMARTIE3$gbifapi_species <- SMARTIE2$ifbl
SMARTIE3$gbifapi_speciesKey <- SMARTIE2$countryCode
SMARTIE3$gbifapi_status <- SMARTIE2$dataGeneralizations
SMARTIE3$gbifapi_usageKey <- SMARTIE2$datasetName
SMARTIE3$geodeticDatum <- SMARTIE2$dateIdentified
SMARTIE3$habitat <- NA
SMARTIE3$identificationRemarks <- NA
SMARTIE3$identificationVerificationStatus <- SMARTIE2$date_length
SMARTIE3$identifiedBy <- NA
SMARTIE3$ifbl <- NA
SMARTIE3$index <- SMARTIE2$decimalLatitude
SMARTIE3$individualCount <- SMARTIE2$decimalLongitude
SMARTIE3$institutionCode <- NA
SMARTIE3$lifeStage <- NA
SMARTIE3$lifestage <- NA
SMARTIE3$locality <- NA
SMARTIE3$locationRemarks <- NA
SMARTIE3$municipality <- NA
SMARTIE3$occurrenceID <- NA
SMARTIE3$occurrenceRemarks <- NA
SMARTIE3$occurrenceStatus <- NA
SMARTIE3$organismsQuantity <- NA
SMARTIE3$organismsQuantityType <- NA
SMARTIE3$ownerOrganization <- SMARTIE2$gbifapi_matchType
SMARTIE3$recordNumber <- NA
SMARTIE3$recordedBy <- NA
SMARTIE3$reproductiveCondition <- NA
SMARTIE3$samplingProtocol <- SMARTIE2$gbifapi_rank
SMARTIE3$scientificName <- NA
SMARTIE3$sex <- SMARTIE2$gbifapi_scientificName
SMARTIE3$specificEpithet <- NA
SMARTIE3$taxonRank <- NA
SMARTIE3$uuid <- SMARTIE2$gbifapi_species
SMARTIE3$verbatimCoordinateSystem <- SMARTIE2$gbifapi_speciesKey
SMARTIE3$verbatimCoordinates <- NA
SMARTIE3$verbatimDatasetName <- SMARTIE2$gbifapi_status
SMARTIE3$verbatimElevation <- NA
SMARTIE3$verbatimEventDate <- SMARTIE2$gbifapi_usageKey
SMARTIE3$verbatimLatitude <- as.numeric(SMARTIE2$geodeticDatum)
SMARTIE3$verbatimLocality <- SMARTIE2$habitat
SMARTIE3$verbatimLongitude <- as.numeric(SMARTIE2$identificationRemarks)
SMARTIE3$verbatimOccurrenceID <- SMARTIE2$identificationVerificationStatus
SMARTIE3$verbatimSRS <- SMARTIE2$identifiedBy
SMARTIE3$verbatimScientificName <- SMARTIE2$ifbl
SMARTIE3$verbatimVernacularName <- SMARTIE2$individualCount
SMARTIE3$vernacularName <- NA

SMARTIE_FINAL <- rbind(SMARTIE1, SMARTIE3)

No_Species <- subset(SMARTIE_FINAL, is.na(gbifapi_scientificName))
No_Lat <- subset(SMARTIE_FINAL, is.na(decimalLatitude))
Lat <- subset(SMARTIE_FINAL, !is.na(decimalLatitude))
 if(nrow(No_Lat)>0){
   No_Lat$decimalLatitude <- ifelse(!is.na(No_Lat$verbatimLatitude), No_Lat$verbatimLatitude, NA)
   No_Lat$decimalLongitude <- ifelse(!is.na(No_Lat$verbatimLongitude), No_Lat$verbatimLongitude, NA)
 }
SMARTIE_FINAL <- rbind(No_Lat, Lat)
No_Lon <- subset(SMARTIE_FINAL, is.na(decimalLongitude))

SMARTIE_FINAL$decimalLatitude
```
```{r Cleanup after Smartie split}
remove(SMARTIE1)
remove(SMARTIE2)
remove(SMARTIE3)
remove(No_Lat)
remove(Lat)
remove(No_Lon)
remove(No_Species)
remove(No_verification)
```

```{r Merge SMARTIE and Checklist}

#euConcernstatus is missing from SMARTIE file and should be added using aggregated checklist
temp <- SMARTIE_FINAL
temp2 <- data.frame(aggregated_checklist)

#Correct species name typo's

temp$gbifapi_scientificName <- ifelse(temp$gbifapi_scientificName == "Eichhornia crassipes Solms", "Eichhornia crassipes (Mart.) Solms", temp$gbifapi_scientificName)
temp$gbifapi_scientificName <- ifelse(temp$gbifapi_scientificName == "Elodea nuttallii H.St.John", "Elodea nuttallii (Planch.) H.St.John", temp$gbifapi_scientificName)
temp$gbifapi_scientificName <- ifelse(temp$gbifapi_scientificName == "Eriocheir sinensis H.Milne Edwards, 1853", "Eriocheir sinensis H. Milne Edwards, 1853", temp$gbifapi_scientificName)
temp$gbifapi_scientificName <- ifelse(temp$gbifapi_scientificName == "Hydrocotyle ranunculoides L.f.", "Hydrocotyle ranunculoides L. fil.", temp$gbifapi_scientificName)
temp$gbifapi_scientificName <- ifelse(temp$gbifapi_scientificName == "Ludwigia grandiflora (Michx.) Greuter & Burdet", "Ludwigia grandiflora (Michaux) Greuter & Burdet", temp$gbifapi_scientificName)
temp$gbifapi_scientificName <- ifelse(temp$gbifapi_scientificName == "Ludwigia peploides (Kunth) P.H.Raven", "Ludwigia peploides (Kunth) P. H. Raven", temp$gbifapi_scientificName)
temp$gbifapi_scientificName <- ifelse(temp$gbifapi_scientificName == "Myriophyllum aquaticum Verdc.", "Myriophyllum aquaticum (Vellozo) Verdcourt", temp$gbifapi_scientificName)
temp$gbifapi_scientificName <- ifelse(temp$gbifapi_scientificName == "Persicaria perfoliata (L.) H.Gross", "Truellum perfoliatum (L.) Soják", temp$gbifapi_scientificName)
temp$gbifapi_scientificName <- ifelse(temp$gbifapi_scientificName == "Trachemys scripta (Thunberg In Schoepff, 1792)", "Trachemys scripta Schoepff, 1792", temp$gbifapi_scientificName)
temp$gbifapi_scientificName <- ifelse(temp$gbifapi_scientificName == "Trachemys scripta elegans (Wied, 1838)", "Trachemys scripta Schoepff, 1792", temp$gbifapi_scientificName)
temp$gbifapi_scientificName <- ifelse(temp$gbifapi_scientificName == "Trachemys scripta scripta", "Trachemys scripta Schoepff, 1792", temp$gbifapi_scientificName)
temp$gbifapi_scientificName <- ifelse(temp$gbifapi_scientificName == "Trachemys scripta troostii (Holbrook, 1836)", "Trachemys scripta Schoepff, 1792", temp$gbifapi_scientificName)

#Merge SMARTIE to Checklist
SMARTIE_FINAL2 <- merge(x= temp, y = temp2, by.x = "gbifapi_scientificName", by.y = "gbifapi_acceptedScientificName", all.x=T)

#Set correct euConcernStatus
SMARTIE_FINAL2$euConcernStatus <- ifelse(SMARTIE_FINAL2$gbifapi_scientificName == "Trachemys scripta Schoepff, 1792", "Listed", SMARTIE_FINAL2$euConcernStatus)

#Detect errors
#Remaining species should not be Listed, under consideration nor under preparation
temp3 <- subset(SMARTIE_FINAL2, is.na(euConcernStatus))
table(temp3$gbifapi_scientificName)
```
```{r Cleanup merge SMARTIE to Checklist}
remove(temp)
remove(temp2)
remove(temp3)
```

```{r Set correct column names for merge}
#Columns in SMARTIE_FINAL who do not appear in T0
#SMARTIE_FINAL2$habitat <- SMARTIE_FINAL2$habitat.x
SMARTIE_FINAL2$habitat.x <- NULL
SMARTIE_FINAL2$habitat.y <- NULL
SMARTIE_FINAL2$associatedTaxa <- NULL
SMARTIE_FINAL2$Modified <- NULL
SMARTIE_FINAL2$gbifapi_rank <- NULL
SMARTIE_FINAL2$gbifapi_usageKey <- NULL
SMARTIE_FINAL2$nativeRange <- NULL
SMARTIE_FINAL2$collectionID <- NULL
SMARTIE_FINAL2$ProviderID <- NULL
SMARTIE_FINAL2$introductionPathway <- NULL
SMARTIE_FINAL2$firstObservationYearBE <- NULL
SMARTIE_FINAL2$gbifapi_status <- NULL
SMARTIE_FINAL2$fips <- NULL
SMARTIE_FINAL2$firstAppearance <- NULL
SMARTIE_FINAL2$datasetName <- SMARTIE_FINAL2$datasetName.x
SMARTIE_FINAL2$datasetName.x <- NULL
SMARTIE_FINAL2$datasetName.y <- NULL
SMARTIE_FINAL2$FilenameID <- NULL
SMARTIE_FINAL2$firstObservationYearFL <- NULL
SMARTIE_FINAL2$presenceWA <- NULL
SMARTIE_FINAL2$presenceBE <- NULL
SMARTIE_FINAL2$presenceBR <- NULL
SMARTIE_FINAL2$presenceFL <- NULL
SMARTIE_FINAL2$invasionStage <- NULL
SMARTIE_FINAL2$reproductiveCondition <- NULL
SMARTIE_FINAL2$gbifapi_species <- NULL
SMARTIE_FINAL2$behavior <- NULL
SMARTIE_FINAL2$lifeStage <- NULL
SMARTIE_FINAL2$lifestage <- NULL
#SMARTIE_FINAL2$index <- SMARTIE_FINAL2$index.x
SMARTIE_FINAL2$index.x <- NULL
SMARTIE_FINAL2$index.y <- NULL
SMARTIE_FINAL2$ObjectID <- NULL
SMARTIE_FINAL2$locationRemarks <- NULL
SMARTIE_FINAL2$gbifapi_matchType <- NULL
SMARTIE_FINAL2$StateProvince <- NULL
SMARTIE_FINAL2$date_length <- NULL
SMARTIE_FINAL2$uuid <- NULL
SMARTIE_FINAL2$Fiche_ID <- NULL
SMARTIE_FINAL2$identificationRemarks <- NULL
SMARTIE_FINAL2$file_patch <- NULL
SMARTIE_FINAL2$verbatimElevation <- NULL

SMARTIE_FINAL2$ifbl <- NULL

#Columns in T0 who do not appear in SMARTIE_FINAL
SMARTIE_FINAL2$taxonKey <- SMARTIE_FINAL2$gbifapi_speciesKey
SMARTIE_FINAL2$gbifapi_speciesKey <- NULL
SMARTIE_FINAL2$geometry <- as.character(NA)
SMARTIE_FINAL2$year <- lubridate::year(SMARTIE_FINAL2$eventDate)
SMARTIE_FINAL2$gis_utm1_code <- as.character(NA)
SMARTIE_FINAL2$type <- as.character(NA)
SMARTIE_FINAL2$scientificNameID <- as.character(NA)
SMARTIE_FINAL2$license <- as.character(NA)
SMARTIE_FINAL2$scientificNameAuthorship <- as.character(NA)
SMARTIE_FINAL2$source <- "SMARTIE"
SMARTIE_FINAL2$accessRights <- as.character(NA)
SMARTIE_FINAL2$ownerInstitutionCode <- as.character(NA)
SMARTIE_FINAL2$gbifID <- as.character(NA)
SMARTIE_FINAL2$rightsHolder <- as.character(NA)
SMARTIE_FINAL2$language <- as.character(NA)
SMARTIE_FINAL2$waterBody <- as.character(NA)
SMARTIE_FINAL2$gis_EUgrid_cellcode <- as.character(NA)
SMARTIE_FINAL2$organismQuantityType <- as.character(NA)
SMARTIE_FINAL2$gis_bioregion_code <- as.character(NA)
SMARTIE_FINAL2$organismQuantity <- as.character(NA)
SMARTIE_FINAL2$lifeStage <- as.character(NA)
SMARTIE_FINAL2$verbatimSamplingProtocol <- SMARTIE_FINAL2$samplingProtocol
SMARTIE_FINAL2$datasetID <- as.character(NA)
SMARTIE_FINAL2$verbatimTaxonID <- as.character(NA)
SMARTIE_FINAL2$gis_bioregion <- as.character(NA)
SMARTIE_FINAL2$georeferenceRemarks <- as.character(NA)
SMARTIE_FINAL2$eventID <- as.character(NA)
SMARTIE_FINAL2$gbifapi_acceptedScientificName <- SMARTIE_FINAL2$gbifapi_scientificName
SMARTIE_FINAL2$gbifapi_scientificName <- NULL
SMARTIE_FINAL2$scientificName_y <- as.character(NA)
SMARTIE_FINAL2$scientificName_x <- as.character(NA)
SMARTIE_FINAL2$dynamicProperties <- as.character(NA)
SMARTIE_FINAL2$taxonID <- as.character(NA)
SMARTIE_FINAL2$coordinatePrecision <- as.character(NA)
SMARTIE_FINAL2$continent <- "Europe"

#Set correct column types

setdiff(T0, SMARTIE_FINAL2)
setdiff(SMARTIE_FINAL2, T0)
```

