---
title: "Replacement EASIN.accdb"
author: "Sander"
date: "6 februari 2018"
output: html_document
---
## Prep

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r libraries}
library(foreign)
library(dplyr)
library(readr)
```

## Read Data

```{r Read Data}
Driveletter <- "D"

fileroot <- paste(Driveletter, "://Projects/PRJ_Faunabeheer/INBOPRJ-10217 - Monitoring exoten ikv EU- verordening IAS  Coördinatie, voorbereiding, implementatie en opvolging/EASIN_GIS/AWS Output/", sep="")
fileroot2 <- paste(Driveletter, "://Projects/PRJ_Faunabeheer/INBOPRJ-10217 - Monitoring exoten ikv EU- verordening IAS  Coördinatie, voorbereiding, implementatie en opvolging/EASIN_GIS/temp/", sep="")

filepath_EASIN <- paste(fileroot, "EASIN.dbf", sep="")
filepath_Grid10k <- paste(fileroot2, "GRID10k.dbf", sep="")
filepath_tbl_T0 <- paste(fileroot, "GRID_ALL.dbf", sep="")

exists(filepath_tbl_T0)

EASIN_raw <- read.dbf(filepath_EASIN)
Grid10k_raw <- read.dbf(filepath_Grid10k)
tbl_T0_raw <- read.dbf(filepath_tbl_T0)

```

## Redux
```{r Q_EASIN_Redux}

EASIN <- EASIN_raw[, c("CellCode", "SPEC", "REFERENCE_", "DATA_PARTN")]

CellCodes <- unique(EASIN$CellCode)
temp5 <- data.frame(1)
temp6 <- data.frame()
for(c in CellCodes){
  temp <- subset(EASIN, CellCode == c)
  Species <- unique(temp$SPEC)
  for(s in Species){
    temp2 <- subset(temp, SPEC == s)
    References <- unique(temp2$REFERENCE_)
    for(r in References){
      temp3 <- subset(temp2, REFERENCE_ == r)
      Data_Partners <- unique(temp3$DATA_PARTN)
      for(d in Data_Partners){
        temp5$CELLCODE <- c
        temp5$SPEC <- s
        temp5$REFERENCE_ <- r
        temp5$DATA_PARTN <- d
        temp6 <- rbind(temp6, temp5)
      }
    }
  }
}

EASIN <- temp6
EASIN$EASIN <- 1
EASIN$X1 <- NULL
```
```{r Clean Up}
remove(temp)
remove(temp2)
remove(temp3)
remove(temp5)
remove(temp6)
remove(CellCodes)
remove(References)
remove(Species)
remove(Data_Partners)
remove(c)
remove(r)
remove(s)
remove(d)

```
```{r Q_T0_Redux}

tbl_T0 <- tbl_T0_raw[, c("CellCode", "SPEC")]

CellCodes <- unique(tbl_T0$CellCode)
temp2 <- data.frame(1)
temp3 <- data.frame()
for(c in CellCodes){
  temp <- subset(tbl_T0, CellCode == c)
  Species <- unique(temp$SPEC)
  for(s in Species){
    temp2$CELLCODE <- c
    temp2$SPEC <- s
    temp3 <- rbind(temp3, temp2)
  }
}
temp3$X1 <- NULL
tbl_T0 <- temp3
tbl_T0$T0 <- 1

```
```{r Clean Up}
remove(temp)
remove(temp2)
remove(temp3)
remove(CellCodes)
remove(Species)
remove(c)
remove(s)
```
## Analyse

```{r Q_EASINandT0, Q_OnlyEasin, Q_OnlyT0}

Samen <- merge(x = EASIN, y = tbl_T0, by.x = c("CELLCODE", "SPEC"), by.y = c("CELLCODE", "SPEC"), all=T)
Samen$T0 <- ifelse(is.na(Samen$T0), 0,Samen$T0)
Samen$EASIN <- ifelse(is.na(Samen$EASIN), 0,Samen$EASIN)

EASINandT0 <- subset(Samen, T0 == 1 & EASIN == 1)
OnlyEASIN <- subset(Samen, T0 == 0 & EASIN == 1)
OnlyT0 <- subset(Samen, T0 == 1 & EASIN == 0)

ALL_raw <- rbind(EASINandT0, OnlyEASIN)
ALL_raw <- rbind(ALL_raw, OnlyT0)

ALL_raw$Accepted <- ifelse(ALL_raw$EASIN == 1 & ALL_raw$T0 == 1, "Y", 
                       ifelse(ALL_raw$EASIN == 0 & ALL_raw$T0 == 1, "New",
                              ifelse(ALL_raw$EASIN == 1 & ALL_raw$T0 == 0, "N", NA)))

ALL <-  merge(x = ALL_raw, y = Grid10k_raw, by.x = "CELLCODE",by.y= "CellCode", all.x = T)

ALL <- ALL[,c("CELLCODE", "SPEC", "REFERENCE_", "DATA_PARTN", "Accepted", "X", "Y")]
```
```{r clean up}
remove(Samen)
remove(EASINandT0)
remove(OnlyEASIN)
remove(OnlyT0)
```
## Export
```{r Export}
exportpath <- paste(Driveletter, "://Projects/PRJ_Faunabeheer/INBOPRJ-10217 - Monitoring exoten ikv EU- verordening IAS  Coördinatie, voorbereiding, implementatie en opvolging/EASIN_GIS/Input/ALL.csv", sep="")

write.dbf(ALL, exportpath)
```



